version: "3.9"
services:
  database:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=0000
    ports:
      - "3307:3307"
    volumes:
      - mysql-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  mysql-db: